<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div-MyAccountDropDown</name>
   <tag></tag>
   <elementGuidId>81af645b-99e9-4877-8001-aae720828204</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[id=&quot;header-user-details&quot;]+div</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
