<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ComputerProduct</name>
   <tag></tag>
   <elementGuidId>db8576b6-3b48-43dc-97b7-36250b090775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@href=&quot;/Tags-Forms/Computer-Register/Receipt-Rolls/thermal-bpa-free-21-receipt-rolls-wfront-hanger-and-back-print-50case/&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
