<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_stockNotification</name>
   <tag></tag>
   <elementGuidId>0e6e7988-154f-47e6-9677-796c979d2e53</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.stock-notification</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
