<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_productTitle</name>
   <tag></tag>
   <elementGuidId>ad3e5e37-ac8e-480f-8073-7505b8d5be63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.product-name</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
