<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_selectedColorText</name>
   <tag></tag>
   <elementGuidId>19e9ab0b-e08b-4075-afbd-6eee858e095b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.selected-color-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
