<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_productSKU</name>
   <tag></tag>
   <elementGuidId>cd021724-05b5-4411-ba82-75842c3af8db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.sku-number</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
