<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_packingProductsLink</name>
   <tag></tag>
   <elementGuidId>d4f19638-00f8-4e67-a3f9-6082f53543fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[href=&quot;https://www.cleanersupply.com/search-results/?Category=Packaging+Products&amp;q=Plastic&amp;r=true&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
