<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_tagsAndForm</name>
   <tag></tag>
   <elementGuidId>d92ad681-16e5-491a-84d6-fbce733bc6f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>s//*[@id=&quot;flyout-menu&quot;]/ul</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;flyout-menu&quot;]/ul/li[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
