<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_cartLink</name>
   <tag></tag>
   <elementGuidId>5ab18d0d-0cb0-4b32-bcbd-9db2f44d24de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.cart-holder</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
