<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a-contact-email</name>
   <tag></tag>
   <elementGuidId>1bfc9fd1-855e-4526-9f6f-20bef6bb6161</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.icon-email+a[class=&quot;contact-info&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
