<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a-footer-2col</name>
   <tag></tag>
   <elementGuidId>21baa698-bb96-48aa-b9ab-a895b8d6d2ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;footer-container&quot;]/div[2]/div/div/div[2]/div/div[2]/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
