<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a-footer-3col</name>
   <tag></tag>
   <elementGuidId>0cb232a4-75c6-41d1-8c0a-6c3dc11a5d4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;footer-container&quot;]/div[2]/div/div/div[2]/div/div[3]/div/div[2]/ul/li/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
