<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a-footer-1col</name>
   <tag></tag>
   <elementGuidId>e3c8bda3-689a-4af9-8d12-85e684b82be3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;footer-container&quot;]/div[2]/div/div/div[2]/div/div[1]/div/div[2]/div/ul/li/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
