<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a-leave-feedback</name>
   <tag></tag>
   <elementGuidId>f6e93367-4c2a-4e29-a5b4-709a3e9d893d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>hr+a[data-target=&quot;#leave-feedback-form&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
