<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span-successAlert</name>
   <tag></tag>
   <elementGuidId>0bcf35ff-5660-4aa5-9efb-788bc22551f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[class=&quot;success-message&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
