<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ComputerAndRegister</name>
   <tag></tag>
   <elementGuidId>c0b1f023-f1eb-4d22-87a1-ab07591dbc79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;flyout-menu&quot;]//div[1]/a[@href=&quot;/Tags-Forms/Computer-Register/&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
