<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_TitleOfCheckOutAsGuest</name>
   <tag></tag>
   <elementGuidId>d9bba7d4-410f-485f-95ed-2dcdf02838b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;interstitial-cart&quot;]//div[1]/div[1]/div[2]/div[@class='box__title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
