<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CheckoutAsGuestRadio</name>
   <tag></tag>
   <elementGuidId>757262d8-368c-4e2f-b4f7-ba40ef3133ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;interstitial-cart&quot;]//form/div[1]//label/span[1]/span[@class='custom-checkb']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
