<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body</name>
   <tag></tag>
   <elementGuidId>afeef01d-6bad-4f85-a789-796d877f338e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body.csi</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@class=&quot;csi&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
