<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1-pageHeading</name>
   <tag></tag>
   <elementGuidId>d95790e4-183f-452c-8037-56a9dd00c81f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div>h1</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
