<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2-modal-header</name>
   <tag></tag>
   <elementGuidId>54701c44-7bf3-4908-98e2-63c465c8bad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.modal-body>h2</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
