<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_productPrice</name>
   <tag></tag>
   <elementGuidId>4cb63db3-b4fb-4ca5-a098-039d922bff5c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.product-table__price</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
