<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_totalPrice</name>
   <tag></tag>
   <elementGuidId>d48893b4-5ace-4075-9121-10884e8263a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.product-table__total</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
