<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a-details</name>
   <tag></tag>
   <elementGuidId>e3ede2f9-f84f-48c2-aa50-218b0fa5eed3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[class=&quot;info-action&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
