<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ManufacturerMaterial</name>
   <tag></tag>
   <elementGuidId>31326a62-ce76-4342-a963-26b1d7d0164d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.js-fg-material</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
