<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-remove</name>
   <tag></tag>
   <elementGuidId>8f337b4c-6a23-4c4f-8eb7-3d6001c2e188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td>[type=&quot;button&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
