<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-expirationYear</name>
   <tag></tag>
   <elementGuidId>951b21d2-6780-492c-8bd8-f20ab056ee41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[title=&quot;Year&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
