<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-expirationMonth</name>
   <tag></tag>
   <elementGuidId>1a29df55-6a34-48be-a540-3ff4b6d744a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[title=&quot;Month&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
