<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn-state</name>
   <tag></tag>
   <elementGuidId>33abbf79-7e4d-4e18-a00f-cabec050ba86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[title=&quot;State/Province&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
